export const HOME_LOADING = "HOME_LOADING";
export const HOME_NOT_LOADING = "HOME_NOT_LOADING";

export const BROWSE_IS_LOADING = "BROWSE_IS_LOADING";
export const BROWSE_NOT_LOADING = "BROWSE_NOT_LOADING";

export const FILTER_ON = "FILTER_ON";
export const FILTER_OFF = "FILTER_OFF";

export const FILTER_GENRE_ON = "FILTER_GENRE_ON";
export const FILTER_GENRE_PICK = "FILTER_GENRE_PICK";
export const FILTER_GENRE_OFF = "FILTER_GENRE_OFF";

export const FILTER_YEAR_ON = "FILTER_YEAR_ON";
export const FILTER_YEAR_PICK = "FILTER_YEAR_PICK";
export const FILTER_YEAR_OFF = "FILTER_YEAR_OFF";

export const FILTER_RATING_ON = "FILTER_RATING_ON";
export const FILTER_RATING_PICK = "FILTER_RATING_PICK";
export const FILTER_RATING_OFF = "FILTER_RATING_OFF";

export const FILTER_MOVIE_NAME_ON = "FILTER_MOVIE_NAME_ON";
export const FILTER_MOVIE_NAME_PICK = "FILTER_MOVIE_NAME_PICK";
export const FILTER_MOVIE_NAME_OFF = "FILTER_MOVIE_NAME_OFF";