export const HOME_LOADING = "HOME_LOADING";
export const HOME_NOT_LOADING = "HOME_NOT_LOADING";
export const BROWSE_IS_LOADING = "BROWSE_IS_LOADING";
export const BROWSE_NOT_LOADING = "BROWSE_NOT_LOADING";